### ISSUE TITLE
Can't install Wolvenkit-Resources

### ISSUE THREAD

**Issue by vannoo67** [WolvenKit/Wolvenkit-Resources#2]
When I attempt to install the Wolvenkit-Resources from either wolvenkit-8.10 or wolvenkit-8.11.0-nightly, the red progress-bar sweeps across the screen once, then stops, silently failing. The install button is still visible, rather than being replaced with Repair, Open, Remove buttons.

I have tried installing the other plugins, they all install correctly.

Did something break with the latest release (6 hours ago)

**Comment by Simarilius-uk** [comment]
its in the middle of being upgraded to work with the latest game version

**Comment by vannoo67** [comment]
Is there a version / combination that does work?

**Comment by vannoo67** [comment]
I guess that's a no. Looks like I picked an unlucky time to try Wolvenkit.
Best wishes with the upgrade. I'll have another look in a few days.

**Comment by seberoth** [comment]
Looks like we don't provide 24/7 support...
Also the WolvenKit repo or Discord would be a better place to ask.

1.6.1 works with up to the 2023-10-5 nightly.
2.0.0 works with the nightlies starting from today

**Comment by vannoo67** [comment]
Can confirm that the latest release has fixed my problem.
Very much appreciate the feedback and the fix.
Can't say I appreciate the snotty language. 
I stand by my statement - I did pick an unlucky time to try WolvenKit (and the WolvenKit-Resources plugin) in the 8 hour window that it was broken

**Comment by seberoth** [comment]
Sorry for the "snotty" language. Seems its not my day today.

Just getting kind of mad, when I see people writing things like "I guess that's a no" when we doesn't response in an one hour time frame.
After all this is an open-source project where people are doing the development and support in their free time.

**Comment by vannoo67** [comment]
I appreciate that and all of the hard work you put in to produce such a great product.
I guess some of my language was a bit snotty too.
Keep up the good work

**Comment by 4Brad-23** [comment]
Why there's no mention of manual installation - the "red.kark" file where do I put it?

**Comment by manavortex** [comment]
Because you don't install anything manually :)
